In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import LabelEncoder

from sklearn.linear_model import LinearRegression

from sklearn.tree import DecisionTreeRegressor

from sklearn.ensemble import RandomForestRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("../data/processed/glassdoor_jobs_cleaned.csv")

df.head()

,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors,Min Salary,Max Salary,Average Salary,Company Age,State
0,Data Scientist,53-91,"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1,53.0,91.0,72.0,53.0,NM
1,Healthcare Data Scientist,63-112,What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1,63.0,112.0,87.5,42.0,MD
2,Data Scientist,80-90,"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1,80.0,90.0,85.0,16.0,FL
3,Data Scientist,56-97,*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa...",56.0,97.0,76.5,61.0,WA
4,Data Scientist,86-143,Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee",86.0,143.0,114.5,28.0,NY

In [3]:
df.isnull().sum()

Job Title              0
Salary Estimate        0
Job Description        0
Rating                 0
Company Name           0
Location               0
Headquarters           0
Size                   0
Founded                0
Type of ownership      0
Industry               0
Sector                 0
Revenue                0
Competitors            0
Min Salary           214
Max Salary           214
Average Salary       214
Company Age           97
State                  0
dtype: int64

In [4]:
drop_cols = [
    "Salary Estimate",
    "Job Description",
    "Headquarters",
    "Competitors"
]

df = df.drop(columns=drop_cols, errors="ignore")

In [5]:
df.head()

,Job Title,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min Salary,Max Salary,Average Salary,Company Age,State
0,Data Scientist,3.8,Tecolote Research,"Albuquerque, NM",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),53.0,91.0,72.0,53.0,NM
1,Healthcare Data Scientist,3.4,University of Maryland Medical System,"Linthicum, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),63.0,112.0,87.5,42.0,MD
2,Data Scientist,4.8,KnowBe4,"Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),80.0,90.0,85.0,16.0,FL
3,Data Scientist,3.8,PNNL,"Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),56.0,97.0,76.5,61.0,WA
4,Data Scientist,2.9,Affinity Solutions,"New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,86.0,143.0,114.5,28.0,NY

In [6]:
num_cols = df.select_dtypes(include=np.number).columns

for col in num_cols:
    df[col].fillna(df[col].median(), inplace=True)

In [7]:
cat_cols = df.select_dtypes(include="object").columns

for col in cat_cols:
    df[col].fillna(df[col].mode()[0], inplace=True)

In [9]:
# One-Hot Encode categorical columns
df = pd.get_dummies(df, drop_first=True)

df.head()

,Job Title,Rating,Company Name,Location,Size,Founded,Type of ownership,Industry,Sector,Revenue,Min Salary,Max Salary,Average Salary,Company Age,State
0,87,3.8,391,3,6,1973,2,3,2,9,53.0,91.0,72.0,53.0,27
1,138,3.4,420,120,2,1984,8,28,12,5,63.0,112.0,87.5,42.0,18
2,87,4.8,216,50,6,2010,2,48,6,4,80.0,90.0,85.0,16.0,8
3,87,3.8,290,183,3,1965,5,18,19,10,56.0,97.0,76.5,61.0,43
4,87,2.9,15,147,7,1998,2,2,6,13,86.0,143.0,114.5,28.0,28

In [10]:
X = df.drop("Average Salary", axis=1)
y = df["Average Salary"]

In [11]:
# Convert categorical variables into dummy variables
df = pd.get_dummies(df, drop_first=True)