In [1]:
# Data Manipulation
import pandas as pd
import numpy as np

# Data Visualization
import matplotlib.pyplot as plt
import seaborn as sns

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Display settings
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
df = pd.read_csv("../Data/raw/glassdoor_jobs.csv")

df.head()

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
0,0,Data Scientist,$53K-$91K (Glassdoor est.),"Data Scientist\nLocation: Albuquerque, NM\nEdu...",3.8,Tecolote Research\n3.8,"Albuquerque, NM","Goleta, CA",501 to 1000 employees,1973,Company - Private,Aerospace & Defense,Aerospace & Defense,$50 to $100 million (USD),-1
1,1,Healthcare Data Scientist,$63K-$112K (Glassdoor est.),What You Will Do:\n\nI. General Summary\n\nThe...,3.4,University of Maryland Medical System\n3.4,"Linthicum, MD","Baltimore, MD",10000+ employees,1984,Other Organization,Health Care Services & Hospitals,Health Care,$2 to $5 billion (USD),-1
2,2,Data Scientist,$80K-$90K (Glassdoor est.),"KnowBe4, Inc. is a high growth information sec...",4.8,KnowBe4\n4.8,"Clearwater, FL","Clearwater, FL",501 to 1000 employees,2010,Company - Private,Security Services,Business Services,$100 to $500 million (USD),-1
3,3,Data Scientist,$56K-$97K (Glassdoor est.),*Organization and Job ID**\nJob ID: 310709\n\n...,3.8,PNNL\n3.8,"Richland, WA","Richland, WA",1001 to 5000 employees,1965,Government,Energy,"Oil, Gas, Energy & Utilities",$500 million to $1 billion (USD),"Oak Ridge National Laboratory, National Renewa..."
4,4,Data Scientist,$86K-$143K (Glassdoor est.),Data Scientist\nAffinity Solutions / Marketing...,2.9,Affinity Solutions\n2.9,"New York, NY","New York, NY",51 to 200 employees,1998,Company - Private,Advertising & Marketing,Business Services,Unknown / Non-Applicable,"Commerce Signals, Cardlytics, Yodlee"

In [3]:
print("Rows :", df.shape[0])
print("Columns :", df.shape[1])

Rows : 956
Columns : 15

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 956 entries, 0 to 955
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         956 non-null    int64
 1   Job Title          956 non-null    object
 2   Salary Estimate    956 non-null    object
 3   Job Description    956 non-null    object
 4   Rating             956 non-null    float64
 5   Company Name       956 non-null    object
 6   Location           956 non-null    object
 7   Headquarters       956 non-null    object
 8   Size               956 non-null    object
 9   Founded            956 non-null    int64
 10  Type of ownership  956 non-null    object
 11  Industry           956 non-null    object
 12  Sector             956 non-null    object
 13  Revenue            956 non-null    object
 14  Competitors        956 non-null    object
dtypes: float64(1), int64(2), object(12)
memory usage: 112.2+ KB

In [5]:
df.columns.tolist()

['Unnamed: 0',
 'Job Title',
 'Salary Estimate',
 'Job Description',
 'Rating',
 'Company Name',
 'Location',
 'Headquarters',
 'Size',
 'Founded',
 'Type of ownership',
 'Industry',
 'Sector',
 'Revenue',
 'Competitors']

In [6]:
df.describe()

       Unnamed: 0      Rating      Founded
count  956.000000  956.000000   956.000000
mean   477.500000    3.601255  1774.605649
std    276.117729    1.067619   598.942517
min      0.000000   -1.000000    -1.000000
25%    238.750000    3.300000  1937.000000
50%    477.500000    3.800000  1992.000000
75%    716.250000    4.200000  2008.000000
max    955.000000    5.000000  2019.000000

In [7]:
df.describe(include="object") # pyright: ignore[reportArgumentType]

,Job Title,Salary Estimate,Job Description,Company Name,Location,Headquarters,Size,Type of ownership,Industry,Sector,Revenue,Competitors
count,956,956,956,956,956,956,956,956,956,956,956,956
unique,328,417,596,448,237,235,9,13,63,25,14,149
top,Data Scientist,-1,Palermo Villa Inc. is interested in a high-ene...,Reynolds American\n3.1,"New York, NY","New York, NY",1001 to 5000 employees,Company - Private,Biotech & Pharmaceuticals,Information Technology,Unknown / Non-Applicable,-1
freq,178,214,4,14,78,75,177,532,148,239,299,634

In [8]:
missing_values = pd.DataFrame({
    "Missing Values": df.isnull().sum(),
    "Percentage": (df.isnull().sum()/len(df))*100
})

missing_values.sort_values("Percentage", ascending=False)

                   Missing Values  Percentage
Unnamed: 0                      0         0.0
Job Title                       0         0.0
Salary Estimate                 0         0.0
Job Description                 0         0.0
Rating                          0         0.0
Company Name                    0         0.0
Location                        0         0.0
Headquarters                    0         0.0
Size                            0         0.0
Founded                         0         0.0
Type of ownership               0         0.0
Industry                        0         0.0
Sector                          0         0.0
Revenue                         0         0.0
Competitors                     0         0.0

In [9]:
print("Duplicate Rows:", df.duplicated().sum())

Duplicate Rows: 0

In [10]:
for column in df.columns:
    print(f"{column}: {df[column].nunique()} unique values")

Unnamed: 0: 956 unique values
Job Title: 328 unique values
Salary Estimate: 417 unique values
Job Description: 596 unique values
Rating: 32 unique values
Company Name: 448 unique values
Location: 237 unique values
Headquarters: 235 unique values
Size: 9 unique values
Founded: 109 unique values
Type of ownership: 13 unique values
Industry: 63 unique values
Sector: 25 unique values
Revenue: 14 unique values
Competitors: 149 unique values

In [11]:
df.sample(5)

,Unnamed: 0,Job Title,Salary Estimate,Job Description,Rating,Company Name,Location,Headquarters,Size,Founded,Type of ownership,Industry,Sector,Revenue,Competitors
811,811,Data Analyst Chemist - Quality System Contractor,$61K-$110K (Glassdoor est.),The Opportunity:\n\nThis is a Contract role th...,2.2,"Rodan and Fields, LLC\n2.2","San Francisco, CA","San Francisco, CA",501 to 1000 employees,2002,Company - Private,Beauty & Personal Accessories Stores,Retail,Unknown / Non-Applicable,-1
884,884,Data Scientist (Warehouse Automation),$79K-$127K (Glassdoor est.),"SoftBank Robotics, the global leader in workfo...",3.8,SoftBank Robotics\n3.8,"San Francisco, CA","Paris, France",201 to 500 employees,2005,Subsidiary or Business Segment,Consumer Products Manufacturing,Manufacturing,$25 to $50 million (USD),-1
278,278,System and Data Analyst,$42K-$76K (Glassdoor est.),Overview\n\n\nCorcentric is a leading provider...,3.7,Corcentric\n3.7,"Cherry Hill, NJ","Cherry Hill, NJ",201 to 500 employees,1996,Company - Private,Enterprise Software & Network Solutions,Information Technology,Unknown / Non-Applicable,-1
540,540,Data Scientist,$56K-$95K (Glassdoor est.),"Sartorius Stedim Data Analytics, a market lead...",3.5,Sartorius\n3.5,"Albuquerque, NM","Gottingen, Germany",5001 to 10000 employees,1870,Company - Public,Biotech & Pharmaceuticals,Biotech & Pharmaceuticals,$1 to $2 billion (USD),-1
636,636,Data Scientist - Alpha Insights,$129K-$215K (Glassdoor est.),Two Sigma is a different kind of investment ma...,4.4,Two Sigma\n4.4,"New York, NY","New York, NY",1001 to 5000 employees,2001,Company - Private,Investment Banking & Asset Management,Finance,Unknown / Non-Applicable,-1

# Business Context

Technology companies offer different salary packages depending on factors
such as job role, company size, location, industry, and experience.

This project analyzes the Glassdoor Jobs dataset to uncover salary trends
and develop a machine learning model that predicts salaries based on job
attributes.

The insights can help:

- Job Seekers
- HR Teams
- Recruiters
- Organizations

# Problem Statement

The objective of this project is to answer the following questions:

1. How does salary vary by job position?
2. Does company size affect salary?
3. Which locations offer the highest salaries?
4. Which industries pay the highest salaries?
5. Can salary be predicted accurately using job attributes?